### PR TITLE
Check

### PR DESCRIPTION
**Pull request by nayan2306**
I have try it can you please check it once

### CODE REVIEW

**Comment by CS-Aditya-Rawat** [comment]
Are you just copy pasting the code ?

**Comment by nayan2306** [comment]
No I have done on my geeks for Geeks practice can i share my ss?

**Comment by nayan2306** [comment]
I am solving only those questions which I have done in my syballus .

**Comment by CS-Aditya-Rawat** [comment]
But in every problem your template is changing. In the previous question the question is by bhavya jain is written but this template is different.

**Comment by CS-Aditya-Rawat** [comment]
Ok Just try to be consistent with the same template for all question. So another using can easily understand the code and also write the question name on the top.

**Comment by nayan2306** [comment]
Sure I will write it

**Comment by nayan2306** [comment]
Thanks sir .I am new in these field .

**Comment by nayan2306** [comment]
Sir now it showing not accepted why ?

**Pull request merged**
