### PR TITLE
Solution of first 10 questions.

### PR DESCRIPTION
**Pull request by mohittk**

### CODE REVIEW

**Comment by mohittk** [comment]
@CS-Aditya-Rawat Is there any mistake in my PR?

**Comment by CS-Aditya-Rawat** [comment]
Follow the right naming convention just write `questionNumber.cpp`

**Comment by mohittk** [comment]
> Follow the right naming convention just write `questionNumber.cpp`

okay ! I'll update

**Comment by CS-Aditya-Rawat** [comment]
And also add Question name above the code and comment it.

**Comment by mohittk** [comment]
Have a look! @CS-Aditya-Rawat

**Comment by mohittk** [comment]
Done! @CS-Aditya-Rawat

**Pull request merged**
