### PR TITLE
Find all pairs of integer whose sum is equal to given number 

### PR DESCRIPTION
**Pull request by urvashiparashar**
Please review it

### CODE REVIEW

**Comment by CS-Aditya-Rawat** [comment]
This solution contains the bruteForce approach only try to write a more optimize code for this.

**Comment by urvashiparashar** [comment]
Now check please

**Comment by CS-Aditya-Rawat** [comment]
Yes, Right code but you didn't need to clear the previous one. you can just add a comment like more optimized or write the T.C and S.C of other codes, SO it will be more useful to other. Remember it for the next time.

**Comment by urvashiparashar** [comment]
> Yes, Right code but you didn't need to clear the previous one. you can just add a comment like more optimized or write the T.C and S.C of other codes, SO it will be more useful to other. Remember it for the next time.

Okayy sure.

**Pull request merged**
