### PR TITLE
Added solution for :-Find whether an array is a subset of another array

### PR DESCRIPTION
**Pull request by gssp4167**
Please check,label it hactoberfest-accepted and merge it.
Thank you

### CODE REVIEW

**Comment by gssp4167** [comment]
Bro...is this project removed from hactoberfest...because for some submissions in this repo,it is showing mature time.But for some submissions it is showing project not participating.

**Comment by CS-Aditya-Rawat** [comment]
I didn't get any notifications like removing the project from hactoberfest. Just wait for some days maybe is doesn't update ig.

**Comment by gssp4167** [comment]
Ok bro

**Comment by gssp4167** [comment]
It is updated only for some submissions it is in mature time...but not for
some submissions....this is happening only with this repo.

**Comment by CS-Aditya-Rawat** [comment]
Ig due to some user just pasted the plagiarized solution. Can you share other repo ?

**Comment by gssp4167** [comment]
https://github.com/open-for-everyone/hacktoberfest2021

Just mail them that this is the case happening for your repo....and above
repo is working perfectly fine

**Pull request merged**
