### PR TITLE
Create 185.py

### PR DESCRIPTION
**Pull request by jen-sjen**
Hey! I'm participating in Hacktoberfest 2k21, requesting you to add the label :)
Good Day!

Program:
To traverse the binary tree and print the left view i.e the leftmost nodes at each level and print it.

### CODE REVIEW

**Comment by CS-Aditya-Rawat** [comment]
Can you change your fileName. Check README

**Comment by jen-sjen** [comment]
It's 185.py

**Comment by jen-sjen** [comment]
Plus, your repo is no more accepted in the hacktoberfest...I guess you need to change the tag with proper spelling

**Comment by CS-Aditya-Rawat** [comment]
I changed the spelling.

**Pull request merged**
