### PR TITLE
Code to Determine if Two Trees are Identical

### PR DESCRIPTION
**Pull request by Mikeflames**

### CODE REVIEW

**Comment by Mikeflames** [comment]
Is this file not up to the mark? Means for merging?

**Comment by CS-Aditya-Rawat** [comment]
use .fileExtension in your filename.

**Comment by CS-Aditya-Rawat** [comment]
use .fileExtension in your filename.

**Comment by Mikeflames** [comment]
Done! Added the file Extension.

**Comment by Mikeflames** [comment]
image
Just Wanted to ask ? Will this PR Count or not in Hactoberfest2021 , as there it is written Project not Participating. please confirm Thanks.

**Pull request merged**
